# Generated by Django 5.0.3 on 2024-09-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zipCode",
            field=models.CharField(default="000000", max_length=10),
            preserve_default=False,
        ),
    ]
